# Generated by Django 3.2.8 on 2021-10-31 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='exprience',
            new_name='experience',
        ),
    ]
