# Generated by Django 3.2.8 on 2021-10-31 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_exprience_service_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='datecreated',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
