# Generated by Django 3.2.8 on 2021-10-31 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_service_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='datecreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
