# Generated by Django 3.2.8 on 2021-11-05 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_service_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='author',
        ),
    ]
