# Generated by Django 3.2.8 on 2021-11-13 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20211113_2004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
