# Generated by Django 3.2.8 on 2021-11-13 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
